# Custom Language File for Launcher Customizer

[ejs.app]
title = "Tily Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Tily-Studio/TilyLauncher"

[ejs.settings]
sourceGithubLink = "https://github.com/Tily-Studio/TilyLauncher"
supportLink = "https://github.com/Tily-Studio/TilyLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO TILYLAUNCHER"
welcomeDescription = "A Minecraft launcher that equips lots of magical modpacks made by Tily Studio."
welcomeDescCTA = "You are just a few clicks away from Tily Launcher."
